#!/usr/bin/env bash
#
# Execute this script to install gremlin on a fresh system

set -euo pipefail

install_git() {
    if which git; then
        return 0
    elif which apt-get; then
        sudo apt-get install -y git
    else
        echo "git not found on path and unable to automatically install"
        exit 1
    fi
}

main() {
    local branch
    local gremlin_dir
    branch="main"
    gremlin_dir="$HOME/.gremlin"

    local OPTARG
    local OPTIND
    while getopts ":hb:d:" opt "${@}"; do
        case ${opt} in
            b)
                branch="$OPTARG"
                ;;
            d)
                gremlin_dir="$OPTARG"
                ;;
            h)
                print_help
                exit 0
                ;;
            ?)
                echo "Invalid option: ${OPTARG}"
                echo ""
                print_help
                exit 1;
                ;;
        esac
    done
    shift $((OPTIND -1))

    if [ "$#" -lt 1 ]; then
        echo "Invalid number of arguments: expected at least 1, received $#"
        echo ""
        print_help
        exit 1
    fi

    install_git

    echo "Cloning branch $branch of the gremlin repository to $gremlin_dir and executing $*"

    git clone --branch "$branch" https://github.com/jmpage/gremlin.git "$gremlin_dir"
    cd "$gremlin_dir"
    ./gremlin "$@"
}

print_help() {
    cat <<EOF
USAGE: $0 [-b branch] [-d directory] [-h] -- <options for gremlin>

EXAMPLE: $0 -b main -d $HOME/.gremlin -- execute personal

Installs gremlin and executes it with the given options

OPTIONS

  -b - the branch to checkout in the gremlin repository (default: main)
  -d - the directory to checkout the gremlin repository to (default: $HOME/.gremlin)
  -h - show this help
EOF
}

main "$@"
