---
# TODO: I don't think this works....
- name: "UI[Gnome/Nautilus]: Set default list view"
  shell: "gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view' || true"

# TODO: These are super hacky and might unbind the wrong thing
# TODO: Break these out into a script to DRY them up
- name: "UI[Shortcuts]: Check for <Control>period"
  register: shortcut_control_period
  shell: "gsettings list-recursively | grep '<Control>period'"
  failed_when: shortcut_control_period.rc < 0 or shortcut_control_period.rc > 1

- name: "UI[Shortcuts]: Unbind <Control>period"
  command:
    cmd: "gsettings set org.freedesktop.ibus.panel.emoji hotkey '[]'"
  when: shortcut_control_period.rc == 0

- name: "UI[Shortcuts]: Check for <Alt>space"
  register: shortcut_alt_space
  shell: "gsettings list-recursively | grep '<Alt>space'"
  failed_when: shortcut_alt_space.rc < 0 or shortcut_alt_space.rc > 1

- name: "UI[Shortcuts]: Unbind <Alt>space"
  command:
    cmd: "gsettings set org.gnome.desktop.wm.keybindings activate-window-menu '[]'"
  when: shortcut_alt_space.rc == 0

# TODO rebind for Ubuntu: org.gnome.Terminal.Legacy.Keybindings
#local profile = $(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')

#gsettings set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 150

#dconf write /org/gnome/terminal/legacy/keybindings/copy "'<Super>c'" # default <Control><Shift>c
#dconf write /org/gnome/terminal/legacy/keybindings/paste "'<Super>v'" # default <Control><Shift>v
